services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
  app:
    # VERVANG DIT DOOR JOUW IMAGE URL (zie stap 4)
    # Let op: alles in kleine letters!
    image: ghcr.io/s4ndyp/taskey:latest
    container_name: app
    restart: always
    ports:
      - 80:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskey
    depends_on:
      - mongo
volumes:
  mongo-data: null
networks: {}
